# TCL File Generated by Component Editor 18.1
# Thu Dec 05 22:04:31 CET 2024
# DO NOT MODIFY


# 
# verrin_co "verrin_co" v1.0
#  2024.12.05.22:04:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module verrin_co
# 
set_module_property DESCRIPTION ""
set_module_property NAME verrin_co
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME verrin_co
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL verrin_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file verrin_avalon.vhd VHDL PATH verrin_avalon.vhd TOP_LEVEL_FILE
add_fileset_file control_butee.vhd VHDL PATH control_butee.vhd
add_fileset_file adc.vhd VHDL PATH adc.vhd
add_fileset_file pwm.vhd VHDL PATH pwm.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 address address Input 5
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point cs_n
# 
add_interface cs_n conduit end
set_interface_property cs_n associatedClock clock
set_interface_property cs_n associatedReset ""
set_interface_property cs_n ENABLED true
set_interface_property cs_n EXPORT_OF ""
set_interface_property cs_n PORT_NAME_MAP ""
set_interface_property cs_n CMSIS_SVD_VARIABLES ""
set_interface_property cs_n SVD_ADDRESS_GROUP ""

add_interface_port cs_n cs_n writeresponsevalid_n Output 1


# 
# connection point clk_adc
# 
add_interface clk_adc conduit end
set_interface_property clk_adc associatedClock clock
set_interface_property clk_adc associatedReset ""
set_interface_property clk_adc ENABLED true
set_interface_property clk_adc EXPORT_OF ""
set_interface_property clk_adc PORT_NAME_MAP ""
set_interface_property clk_adc CMSIS_SVD_VARIABLES ""
set_interface_property clk_adc SVD_ADDRESS_GROUP ""

add_interface_port clk_adc clk_adc writeresponsevalid_n Output 1


# 
# connection point data_adc
# 
add_interface data_adc conduit end
set_interface_property data_adc associatedClock clock
set_interface_property data_adc associatedReset ""
set_interface_property data_adc ENABLED true
set_interface_property data_adc EXPORT_OF ""
set_interface_property data_adc PORT_NAME_MAP ""
set_interface_property data_adc CMSIS_SVD_VARIABLES ""
set_interface_property data_adc SVD_ADDRESS_GROUP ""

add_interface_port data_adc data_adc beginbursttransfer Input 1


# 
# connection point out_sens
# 
add_interface out_sens conduit end
set_interface_property out_sens associatedClock clock
set_interface_property out_sens associatedReset ""
set_interface_property out_sens ENABLED true
set_interface_property out_sens EXPORT_OF ""
set_interface_property out_sens PORT_NAME_MAP ""
set_interface_property out_sens CMSIS_SVD_VARIABLES ""
set_interface_property out_sens SVD_ADDRESS_GROUP ""

add_interface_port out_sens out_sens writeresponsevalid_n Output 1


# 
# connection point pwm_out
# 
add_interface pwm_out conduit end
set_interface_property pwm_out associatedClock clock
set_interface_property pwm_out associatedReset reset
set_interface_property pwm_out ENABLED true
set_interface_property pwm_out EXPORT_OF ""
set_interface_property pwm_out PORT_NAME_MAP ""
set_interface_property pwm_out CMSIS_SVD_VARIABLES ""
set_interface_property pwm_out SVD_ADDRESS_GROUP ""

add_interface_port pwm_out pwm_out writeresponsevalid_n Output 1

